apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-dneb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-dneb
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-dneb
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-dneb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-dneb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-ijsd-tenant/appstudio/dc-metro-map-dneb@sha256:428a48088de039d809532d0ab0f6809cac68d57dbb89314320e008c06c18052b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
