apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-cj7o
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-cj7o
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-cj7o
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-cj7o
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-cj7o
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/push-pyxis-ijsd-tenant/appstudio/devfile-sample-python-basic-cj7o@sha256:8b4714a376c392050672f2b4e97a77a7f9313af852b9f1679d9c44094f557ebd
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
